# to run from the dev, please run jekyll like this:
# jekyll serve --watch --config _config.yml,_config-dev.yml
name: organic living
description: "true organic, chemical free living"
pygments: true
paginate: 10
safe: true
lsi: false
markdown: rdiscount
exclude_from_search: true
url: http://richardjoo.github.io/organicliving

# in order for you to use search (jekyll-lunr-js-search), you need to install
#     gem install json
#     gem install nokogiri